# Generated by Django 4.1 on 2022-08-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('appetizers', 'appetizers'), ('treats', 'treats'), ('drinks', 'drinks'), ('entrees', 'entrees')], max_length=60),
        ),
    ]
