# Generated by Django 4.1 on 2022-08-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prefix',
            field=models.CharField(blank=True, choices=[('Ms.', 'Ms.'), ('Mr.', 'Mr.'), ('Dr.', 'Dr.'), ('Mrs.', 'Mrs.')], max_length=60, null=True),
        ),
    ]
