# Generated by Django 4.1 on 2022-08-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(blank=True, choices=[('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Dr.', 'Dr.'), ('Ms.', 'Ms.')], max_length=60, null=True),
        ),
    ]
